### ISSUE TITLE
Process SpawnProcess-1: Exception in thread Thread-1: Traceback (most recent call last):   File "D:\Anaconda\envs\spert-ch\lib\multiprocessing\connection.py", line 306, in _recv_bytes     ov, err = _winapi.ReadFile(self._handle, bsize, BrokenPipeError: [WinError 109] 管道已结束。  During handling of the above exception, another exception occurred:   File "D:\Anaconda\envs\spert-ch\lib\multiprocessing\connection.py", line 221, in recv_bytes UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 3: illegal multibyte sequence     buf = self._recv_bytes(maxlength)   File "D:\Anaconda\envs\spert-ch\lib\multiprocessing\connection.py", line 326, in _recv_bytes     raise EOFError EOFError

### ISSUE THREAD

**Issue by vv521** [taishan1994/SpERT_chinese#11]
跑到最后，模型保存时出现这个问题，如何解决

**Comment by vv521** [comment]
> 跑到最后，模型保存时出现这个问题，如何解决

是训练的时候出错

**Comment by taishan1994** [comment]
只能单卡训练。

**Comment by tofutoo** [comment]
> 只能单卡训练。

这个是编码格式的错误吧？我也遇到了这个问题
