### ISSUE TITLE
换数据集运行报错

### ISSUE THREAD

**Issue by NYN921** [taishan1994/SpERT_chinese#7]
我换了自己的数据集但是格式调整的一样，一直出现下面错误是为什么
Parse dataset 'train':   0% 0/1 [00:00<?, ?it/s]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/My Drive/SPERT中文/spert.py", line 16, in __train
    trainer.train(train_path=run_args.train_path, valid_path=run_args.valid_path,
  File "/content/drive/My Drive/SPERT中文/spert/spert_trainer.py", line 52, in train
    train_dataset = input_reader.read(train_path, train_label)
  File "/content/drive/My Drive/SPERT中文/spert/input_reader.py", line 122, in read
    self._parse_dataset(dataset_path, dataset)
  File "/content/drive/My Drive/SPERT中文/spert/input_reader.py", line 129, in _parse_dataset
    self._parse_document(document, dataset)
  File "/content/drive/My Drive/SPERT中文/spert/input_reader.py", line 145, in _parse_document
    relations = self._parse_relations(jrelations, entities, dataset)
  File "/content/drive/My Drive/SPERT中文/spert/input_reader.py", line 181, in _parse_relations
    tail = entities[tail_idx]
IndexError: list index out of range

**Comment by taishan1994** [comment]
实体的索引和实体不对应。
